INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (1, 'Daniel', 'Wilson', 'Female', 33, 98.01, 138.16, 'Bronchitis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (2, 'Erik', 'Andrews', 'Male', 51, 37.79, 182.62, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (3, 'Connie', 'Patton', 'Male', 84, 46.1, 163.64, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (4, 'Alex', 'Pacheco', 'Male', 24, 47.58, 168.66, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (5, 'John', 'Jones', 'Female', 76, 41.59, 176.41, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (6, 'Sarah', 'Wilson', 'Male', 55, 56.82, 157.33, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (7, 'Steven', 'Goodwin', 'Female', 88, 39.49, 143.97, 'Bronchitis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (8, 'Maria', 'Tucker', 'Male', 62, 55.16, 174.43, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (9, 'Jasmine', 'Davis', 'Male', 67, 54.59, 179.77, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (10, 'Cynthia', 'Smith', 'Female', 40, 91.04, 156.73, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (11, 'Brittany', 'Hickman', 'Female', 22, 56.71, 130.42, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (12, 'Shelly', 'Snyder', 'Male', 42, 98.24, 174.3, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (13, 'Deanna', 'Tyler', 'Male', 22, 30.11, 139.37, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (14, 'Troy', 'Knox', 'Female', 77, 38.51, 171.07, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (15, 'Joseph', 'Vargas', 'Male', 54, 78.56, 157.57, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (16, 'Tonya', 'Keller', 'Female', 79, 43.81, 188.39, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (17, 'Chase', 'Robbins', 'Male', 44, 80.73, 149.31, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (18, 'Richard', 'Hays', 'Male', 39, 84.02, 181.68, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (19, 'Gregory', 'Carlson', 'Male', 79, 46.02, 148.0, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (20, 'Mario', 'Carey', 'Male', 36, 43.35, 133.75, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (21, 'Andrew', 'Nelson', 'Female', 68, 78.79, 146.67, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (22, 'David', 'Moore', 'Female', 50, 62.18, 181.96, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (23, 'Gavin', 'Parker', 'Female', 80, 61.39, 156.41, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (24, 'Rebecca', 'Leon', 'Female', 28, 97.8, 146.63, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (25, 'Aaron', 'Flores', 'Female', 77, 88.32, 189.54, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (26, 'Jonathan', 'Lowe', 'Male', 38, 47.72, 136.33, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (27, 'Anthony', 'Johnson', 'Female', 84, 46.34, 138.87, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (28, 'Jordan', 'Mcintosh', 'Female', 74, 34.93, 140.0, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (29, 'Ann', 'Montoya', 'Male', 39, 51.32, 177.54, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (30, 'James', 'Medina', 'Male', 39, 56.33, 153.39, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (31, 'Ashley', 'Kelley', 'Female', 71, 65.04, 182.35, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (32, 'Sean', 'Simpson', 'Male', 37, 97.73, 154.45, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (33, 'David', 'Snyder', 'Female', 70, 36.74, 132.29, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (34, 'Whitney', 'Brown', 'Female', 89, 59.55, 141.08, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (35, 'Lisa', 'Pope', 'Male', 89, 46.41, 138.15, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (36, 'Julie', 'Miller', 'Male', 46, 51.73, 143.96, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (37, 'David', 'Lee', 'Male', 84, 92.13, 166.44, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (38, 'Larry', 'Griffin', 'Male', 69, 42.53, 144.03, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (39, 'Allen', 'Owens', 'Female', 58, 70.84, 136.83, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (40, 'Beth', 'Reyes', 'Female', 38, 71.98, 150.16, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (41, 'Albert', 'White', 'Female', 22, 74.13, 165.62, 'Diabetes');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (42, 'Holly', 'Carr', 'Female', 41, 42.49, 167.11, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (43, 'Tyler', 'Wells', 'Female', 26, 64.03, 132.33, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (44, 'Kristi', 'Nelson', 'Female', 57, 69.49, 173.56, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (45, 'Jacqueline', 'Moore', 'Male', 65, 60.11, 166.27, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (46, 'Donald', 'Glover', 'Male', 81, 79.69, 166.64, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (47, 'Catherine', 'Nelson', 'Female', 65, 92.55, 172.09, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (48, 'Lauren', 'Taylor', 'Male', 46, 35.51, 130.23, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (49, 'Brittany', 'Lopez', 'Female', 65, 64.02, 158.39, 'Diabetes');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (50, 'Rachel', 'Spencer', 'Male', 75, 64.87, 135.58, 'Bronchitis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (51, 'James', 'Mccoy', 'Female', 65, 98.57, 173.6, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (52, 'Yolanda', 'Walter', 'Female', 40, 81.43, 179.07, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (53, 'Heather', 'Hale', 'Male', 69, 33.28, 130.85, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (54, 'Nicole', 'Wallace', 'Male', 24, 45.98, 169.6, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (55, 'Charles', 'Rodgers', 'Male', 83, 83.44, 170.75, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (56, 'John', 'Thompson', 'Male', 84, 83.6, 153.27, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (57, 'Jeanne', 'Fields', 'Female', 53, 73.25, 154.67, 'Bronchitis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (58, 'Jessica', 'Lawrence', 'Female', 43, 87.24, 152.77, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (59, 'Michele', 'Beck', 'Male', 36, 93.21, 151.93, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (60, 'Anthony', 'Soto', 'Male', 61, 33.52, 135.51, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (61, 'Katrina', 'Reynolds', 'Female', 66, 31.62, 148.05, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (62, 'Brian', 'White', 'Male', 30, 66.53, 179.82, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (63, 'Kelly', 'Blake', 'Male', 41, 68.48, 181.28, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (64, 'Melinda', 'Foster', 'Male', 42, 34.55, 159.21, 'Influenza');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (65, 'Gregory', 'Russell', 'Male', 85, 45.93, 139.26, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (66, 'Melissa', 'Hart', 'Female', 88, 77.26, 166.39, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (67, 'Sarah', 'Diaz', 'Male', 29, 40.02, 166.62, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (68, 'Jodi', 'Lewis', 'Female', 73, 32.35, 169.14, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (69, 'Pamela', 'Smith', 'Male', 20, 77.89, 164.22, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (70, 'Robert', 'Brooks', 'Female', 26, 73.75, 156.53, 'Diabetes');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (71, 'Willie', 'Huffman', 'Female', 84, 59.18, 174.11, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (72, 'Keith', 'Patel', 'Male', 48, 76.33, 168.7, 'Strep throat');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (73, 'Ashley', 'Mclean', 'Female', 43, 96.58, 137.44, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (74, 'Patrick', 'Hayes', 'Male', 40, 44.36, 150.61, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (75, 'Carla', 'Bray', 'Male', 79, 48.6, 133.33, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (76, 'Renee', 'Francis', 'Female', 40, 48.69, 171.02, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (77, 'Eugene', 'Lee', 'Male', 27, 86.25, 136.15, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (78, 'Martin', 'Martin', 'Male', 55, 82.87, 176.44, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (79, 'Veronica', 'Reed', 'Male', 78, 86.76, 176.87, 'Bronchitis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (80, 'Alexis', 'Meadows', 'Female', 34, 95.38, 168.59, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (81, 'Jeremy', 'Coleman', 'Male', 25, 33.32, 180.07, 'Tuberculosis');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (82, 'Natalie', 'Carter', 'Male', 43, 30.62, 164.39, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (83, 'Kevin', 'Cole', 'Female', 38, 92.46, 150.11, 'Hypertension');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (84, 'Michael', 'Barnett', 'Female', 40, 97.12, 170.64, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (85, 'Kyle', 'Carney', 'Female', 29, 52.34, 162.93, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (86, 'Jessica', 'Kramer', 'Male', 85, 88.81, 178.7, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (87, 'Thomas', 'Long', 'Male', 42, 99.37, 185.08, 'Chickenpox');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (88, 'Gregory', 'Garcia', 'Male', 60, 84.04, 166.29, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (89, 'Brandon', 'Harrington', 'Female', 36, 59.84, 185.56, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (90, 'Jay', 'Dixon', 'Female', 56, 33.87, 148.83, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (91, 'Katherine', 'Hawkins', 'Female', 71, 83.69, 165.34, 'COVID-19');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (92, 'Robert', 'Sanchez', 'Male', 57, 37.88, 137.17, 'Measles');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (93, 'Michelle', 'Anderson', 'Male', 43, 50.76, 136.66, 'Asthma');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (94, 'Juan', 'Ryan', 'Male', 65, 48.27, 181.64, 'Diabetes');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (95, 'Megan', 'Dyer', 'Male', 75, 55.61, 149.68, 'Epilepsy');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (96, 'Evan', 'Gonzales', 'Female', 61, 69.68, 140.18, 'Diabetes');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (97, 'Sharon', 'Lee', 'Female', 88, 71.68, 163.46, 'Coronary heart disease');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (98, 'Kristine', 'Martinez', 'Female', 83, 74.56, 178.97, 'Common cold');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (99, 'Ashley', 'Clark', 'Female', 70, 98.97, 182.83, 'Mumps');
INSERT INTO patient_patient (id, first_name, last_name, gender, age, weight, height, health_history) VALUES (100, 'Annette', 'Martinez', 'Female', 69, 81.81, 182.06, 'Measles');
